var items_recipies1 = {
	"science-pack-1": { name : "Science Pack 1", id : "science-pack-1", recipe : "science-pack-1", energy_required : 5, ingredients : [["copper-plate", 1], ["iron-gear-wheel", 1], ], am_type : "am6", result : 1, },
	"iron-gear-wheel": { name : "Iron Gear Wheel", id : "iron-gear-wheel", recipe : "iron-gear-wheel", energy_required : 0.5, ingredients : [["iron-plate", 2], ], am_type : "am6", result : 1, },
	"iron-plate": { name : "Iron Plate", id : "iron-plate", recipe : "iron-plate", energy_required : 3.5, ingredients : [["iron-ore", 1], ], am_type : "electric_furnace", result : 1, },
	"copper-plate": { name : "Copper Plate", id : "copper-plate", recipe : "copper-plate", energy_required : 3.5, ingredients : [["copper-ore", 1], ], am_type : "electric_furnace", result : 1, },
	"steel-plate": { name : "Steel Plate", id : "steel-plate", recipe : "steel-plate", energy_required : 7, ingredients : [["iron-plate", 2], ], am_type : "electric_furnace", result : 1, },
    "stone-furnace": { name : "stone-furnace", id : "stone-furnace", recipe : "stone-furnace", energy_required : 0.5, ingredients : [["stone", 5], ], am_type : "am6", result : 1, },
    "basic-circuit-board": { name : "Basic Circuit Board", id : "basic-circuit-board", recipe : "basic-circuit-board", energy_required : 1, ingredients : [["wooden-board", 1], ["copper-cable", 3], ], am_type : "am6", result : 1, },
    "wooden-board": { name : "wooden-board", id : "wooden-board", recipe : "wooden-board", energy_required : 0.5, ingredients : [["wood", 1], ], am_type : "am6", result : 2, },
    "wood": { name : "wood", id : "wood", recipe : "wood", energy_required : 0.5, ingredients : [["raw-wood", 1], ], am_type : "am6", result : 2, },
    "copper-cable": { name : "copper-cable", id : "copper-cable", recipe : "copper-cable", energy_required : 0.5, ingredients : [["copper-plate", 1], ], am_type : "am6", result : 2, },
    "electronic-circuit": { name : "Basic Electronic Board", id : "electronic-circuit", recipe : "electronic-circuit", energy_required : 1, ingredients : [["basic-circuit-board", 1], ["basic-electronic-components", 5], ], am_type : "am6", result : 1, },
    "basic-electronic-components": { name : "Basic Electronic Components", id : "basic-electronic-components", recipe : "basic-electronic-components", energy_required : 2, ingredients : [["copper-cable", 1], ["coal", 1], ], am_type : "am6", result : 5, },
    "lab": { name : "lab", id : "lab", recipe : "lab", energy_required : 3, ingredients : [["iron-gear-wheel", 10], ["transport-belt", 4], ["basic-circuit-board", 10], ], am_type : "am6", result : 1, },
    "assembling-machine-2": { name : "assembling-machine-2", id : "assembling-machine-2", recipe : "assembling-machine-2", energy_required : 0.5, ingredients : [["iron-plate", 9], ["electronic-circuit", 3], ["iron-gear-wheel", 5], ["assembling-machine-1", 1], ], am_type : "am6", result : 1, },
    "assembling-machine-1": { name : "assembling-machine-1", id : "assembling-machine-1", recipe : "assembling-machine-1", energy_required : 0.5, ingredients : [["iron-gear-wheel", 5], ["iron-plate", 9], ["basic-circuit-board", 3], ], am_type : "am6", result : 1, },
    "transport-belt": { name : "transport-belt", id : "transport-belt", recipe : "transport-belt", energy_required : 0.5, ingredients : [["iron-plate", 1], ["iron-gear-wheel", 1], ], am_type : "am6", result : 2, },
    "science-pack-2": { name : "science-pack-2", id : "science-pack-2", recipe : "science-pack-2", energy_required : 6, ingredients : [["inserter", 1], ["transport-belt", 1], ], am_type : "am6", result : 1, },
    "inserter": { name : "inserter", id : "inserter", recipe : "inserter", energy_required : 0.5, ingredients : [["iron-gear-wheel", 1], ["iron-plate", 1], ["basic-circuit-board", 1], ], am_type : "am6", result : 1, },
    "gun-turret": { name : "Gun Turret", id : "gun-turret", recipe : "gun-turret", energy_required : 8, ingredients : [["iron-gear-wheel", 10], ["copper-plate", 10], ["iron-plate", 20], ], am_type : "am6", result : 1, },
    "piercing-rounds-magazine": { name : "piercing-rounds-magazine", id : "piercing-rounds-magazine", recipe : "piercing-rounds-magazine", energy_required : 3, ingredients : [["firearm-magazine", 1], ["steel-plate", 1], ["copper-plate", 5], ], am_type : "am6", result : 1, },
    "firearm-magazine": { name : "firearm-magazine", id : "firearm-magazine", recipe : "firearm-magazine", energy_required : 1, ingredients : [["iron-plate", 4], ], am_type : "am6", result : 1, },
    "military-science-pack": { name : "military-science-pack", id : "military-science-pack", recipe : "military-science-pack", energy_required : 10, ingredients : [["piercing-rounds-magazine", 1], ["grenade", 1], ["gun-turret", 1], ], am_type : "am6", result : 2, },
    "grenade": { name : "grenade", id : "grenade", recipe : "grenade", energy_required : 8, ingredients : [["iron-plate", 5], ["coal", 10], ], am_type : "am6", result : 1, },
    "steel-furnace": { name : "steel-furnace", id : "steel-furnace", recipe : "steel-furnace", energy_required : 3, ingredients : [["steel-plate", 6], ["stone-brick", 10], ], am_type : "am6", result : 1, },
    "stone-brick": { name : "stone-brick", id : "stone-brick", recipe : "stone-brick", energy_required : 3.5, ingredients : [["stone", 2], ], am_type : "electric_furnace", result : 1, },
    "bob-sniper-turret-1": { name : "bob-sniper-turret-1", id : "bob-sniper-turret-1", recipe : "bob-sniper-turret-1", energy_required : 20, ingredients : [["iron-gear-wheel", 20], ["copper-plate", 20], ["iron-plate", 20], ], am_type : "am6", result : 1, },
    "plastic-bar": { name : "plastic-bar", id : "plastic-bar", recipe : "plastic-bar", energy_required : 1, ingredients : [["coal", 1], ["petroleum-gas", 20], ], am_type : "chemical_plant", result : 2, },
    "engine-unit": { name : "engine-unit", id : "engine-unit", recipe : "engine-unit", energy_required : 10, ingredients : [["steel-plate", 1], ["iron-gear-wheel", 1], ["pipe", 2], ], am_type : "am6", result : 1, },
    "pipe": { name : "pipe", id : "pipe", recipe : "pipe", energy_required : 0.5, ingredients : [["iron-plate", 1], ], am_type : "am6", result : 1, },
    "science-pack-3": { name : "science-pack-3", id : "science-pack-3", recipe : "science-pack-3", energy_required : 12, ingredients : [["advanced-circuit", 1], ["engine-unit", 1], ["electric-mining-drill", 1], ], am_type : "am6", result : 1, },
    "electric-mining-drill": { name : "electric-mining-drill", id : "electric-mining-drill", recipe : "electric-mining-drill", energy_required : 2, ingredients : [["iron-gear-wheel", 5], ["iron-plate", 10], ["basic-circuit-board", 3], ], am_type : "am6", result : 1, },
    "advanced-circuit": { name : "advanced-circuit", id : "advanced-circuit", recipe : "advanced-circuit", energy_required : 5, ingredients : [["circuit-board", 1], ["basic-electronic-components", 4], ["electronic-components", 4], ], am_type : "am6", result : 1, },
    "circuit-board": { name : "circuit-board", id : "circuit-board", recipe : "circuit-board", energy_required : 5, ingredients : [["phenolic-board", 1], ["copper-plate", 2], ["ferric-chloride-solution", 5], ], am_type : "am6", result : 1, },
    "phenolic-board": { name : "phenolic-board", id : "phenolic-board", recipe : "phenolic-board", energy_required : 0.5, ingredients : [["wood", 1], ["resin", 1], ], am_type : "am6", result : 2, },
    "resin": { name : "bob-resin-wood", id : "resin", recipe : "bob-resin-wood", energy_required : 1, ingredients : [["raw-wood", 1], ], am_type : "am6", result : 1, },
    "electronic-components": { name : "electronic-components", id : "electronic-components", recipe : "electronic-components", energy_required : 3.5, ingredients : [["copper-cable", 1], ["plastic-bar", 1], ["copper-plate", 1], ], am_type : "am6", result : 5, },
    "plastic-bar": { name : "plastic-bar", id : "plastic-bar", recipe : "plastic-bar", energy_required : 1, ingredients : [["coal", 1], ["petroleum-gas", 20], ], am_type : "chemical_plant", result : 2, },
    "module-case": { name : "module-case", id : "module-case", recipe : "module-case", energy_required : 10, ingredients : [["plastic-bar", 2], ["iron-plate", 5], ], am_type : "am6", result : 1, },
    "module-contact": { name : "module-contact", id : "module-contact", recipe : "module-contact", energy_required : 5, ingredients : [["copper-plate", 1], ], am_type : "am6", result : 5, },
    "module-circuit-board": { name : "module-circuit-board", id : "module-circuit-board", recipe : "module-circuit-board", energy_required : 10, ingredients : [["copper-plate", 1], ["phenolic-board", 1], ["ferric-chloride-solution", 5], ], am_type : "am6", result : 1, },
    "module-processor-board": { name : "module-processor-board", id : "module-processor-board", recipe : "module-processor-board", energy_required : 10, ingredients : [["copper-plate", 1], ["phenolic-board", 1], ["ferric-chloride-solution", 5], ], am_type : "am6", result : 4, },
    "speed-processor": { name : "speed-processor", id : "speed-processor", recipe : "speed-processor", energy_required : 2.5, ingredients : [["module-processor-board", 1], ["basic-electronic-components", 2], ["electronic-components", 2], ], am_type : "am6", result : 1, },
    "effectivity-processor": { name : "effectivity-processor", id : "effectivity-processor", recipe : "effectivity-processor", energy_required : 2.5, ingredients : [["module-processor-board", 1], ["basic-electronic-components", 2], ["electronic-components", 2], ], am_type : "am6", result : 1, },
    "productivity-processor": { name : "productivity-processor", id : "productivity-processor", recipe : "productivity-processor", energy_required : 2.5, ingredients : [["module-processor-board", 1], ["basic-electronic-components", 2], ["electronic-components", 2], ], am_type : "am6", result : 1, },
    "pollution-clean-processor": { name : "pollution-clean-processor", id : "pollution-clean-processor", recipe : "pollution-clean-processor", energy_required : 2.5, ingredients : [["module-processor-board", 1], ["basic-electronic-components", 2], ["electronic-components", 2], ], am_type : "am6", result : 1, },
    "pollution-create-processor": { name : "pollution-create-processor", id : "pollution-create-processor", recipe : "pollution-create-processor", energy_required : 2.5, ingredients : [["module-processor-board", 1], ["basic-electronic-components", 2], ["electronic-components", 2], ], am_type : "am6", result : 1, },
    "expansion-bay": { name : "expansion-bay", id : "expansion-bay", recipe : "expansion-bay", energy_required : 15, ingredients : [["electronic-circuit", 10], ["steel-plate", 10], ["copper-cable", 10], ], am_type : "am6", result : 1, },
    "raw-wood": { name : "raw-wood-alt", id : "raw-wood", recipe : "raw-wood-alt", energy_required : 0.01, ingredients : [["coal", 1]], am_type : "am6", result : 100, },
    "lab-module": { name : "lab-module", id : "lab-module", recipe : "lab-module", energy_required : 15, ingredients : [["lab", 1], ["speed-processor", 5], ["effectivity-processor", 5], ["productivity-processor", 5], ], am_type : "am6", result : 1, },
    "intergrated-electronics": { name : "intergrated-electronics", id : "intergrated-electronics", recipe : "intergrated-electronics", energy_required : 5, ingredients : [["copper-cable", 1], ["plastic-bar", 1], ["copper-plate", 2], ["sulfuric-acid", 5], ], am_type : "am6", result : 5, },
    "module-contact": { name : "module-contact", id : "module-contact", recipe : "module-contact", energy_required : 5, ingredients : [["copper-plate", 1], ], am_type : "am6", result : 5, },
    "speed-processor-2": { name : "speed-processor-2", id : "speed-processor-2", recipe : "speed-processor-2", energy_required : 5, ingredients : [["module-processor-board-2", 1], ["electronic-components", 2], ["intergrated-electronics", 2], ], am_type : "am6", result : 1, },
    "effectivity-processor-2": { name : "effectivity-processor-2", id : "effectivity-processor-2", recipe : "effectivity-processor-2", energy_required : 5, ingredients : [["module-processor-board-2", 1], ["electronic-components", 2], ["intergrated-electronics", 2], ], am_type : "am6", result : 1, },
    "productivity-processor-2": { name : "productivity-processor-2", id : "productivity-processor-2", recipe : "productivity-processor-2", energy_required : 5, ingredients : [["module-processor-board-2", 1], ["electronic-components", 2], ["intergrated-electronics", 2], ], am_type : "am6", result : 1, },
    "module-processor-board-2": { name : "module-processor-board-2", id : "module-processor-board-2", recipe : "module-processor-board-2", energy_required : 20, ingredients : [["copper-plate", 1], ["fibreglass-board", 1], ["ferric-chloride-solution", 5], ], am_type : "am6", result : 4, },
    "fibreglass-board": { name : "fibreglass-board", id : "fibreglass-board", recipe : "fibreglass-board", energy_required : 0.5, ingredients : [["plastic-bar", 2], ], am_type : "am6", result : 2, },
    "pollution-clean-processor-2": { name : "pollution-clean-processor-2", id : "pollution-clean-processor-2", recipe : "pollution-clean-processor-2", energy_required : 5, ingredients : [["module-processor-board-2", 1], ["electronic-components", 2], ["intergrated-electronics", 2], ], am_type : "am6", result : 1, },





	

	
	//modules
    "raw-productivity-module-4": { name : "raw-productivity-module-4-combine", id : "raw-productivity-module-4", recipe : "raw-productivity-module-4-combine", energy_required : 60, ingredients : [["productivity-module-4", 1], ["effectivity-module-4", 1], ["pollution-clean-module-4", 1], ], am_type : "am6", result : 1, },
    "raw-speed-module-4": { name : "raw-speed-module-4-combine", id : "raw-speed-module-4", recipe : "raw-speed-module-4-combine", energy_required : 60, ingredients : [["speed-module-4", 1], ["effectivity-module-4", 1], ], am_type : "am6", result : 1, },
    "speed-module-4": { name : "speed-module-4", id : "speed-module-4", recipe : "speed-module-4", energy_required : 40, ingredients : [["speed-module-3", 1], ["speed-processor-2", 4], ["module-contact", 5], ["intergrated-electronics", 5], ], am_type : "am6", result : 1, },
    "speed-module-3": { name : "speed-module-3", id : "speed-module-3", recipe : "speed-module-3", energy_required : 30, ingredients : [["speed-module-2", 1], ["speed-processor-2", 3], ["module-contact", 5], ["electronic-components", 5], ], am_type : "am6", result : 1, },
    "speed-module-2": { name : "speed-module-2", id : "speed-module-2", recipe : "speed-module-2", energy_required : 20, ingredients : [["speed-module", 1], ["speed-processor", 2], ["module-contact", 5], ], am_type : "am6", result : 1, },
    "speed-module": { name : "speed-module", id : "speed-module", recipe : "speed-module", energy_required : 10, ingredients : [["speed-processor", 1], ["module-case", 1], ["module-circuit-board", 1], ["module-contact", 4], ], am_type : "am6", result : 1, },
    "effectivity-module-4": { name : "effectivity-module-4", id : "effectivity-module-4", recipe : "effectivity-module-4", energy_required : 40, ingredients : [["effectivity-module-3", 1], ["effectivity-processor-2", 4], ["module-contact", 5], ["intergrated-electronics", 5], ], am_type : "am6", result : 1, },
    "effectivity-module-3": { name : "effectivity-module-3", id : "effectivity-module-3", recipe : "effectivity-module-3", energy_required : 30, ingredients : [["effectivity-module-2", 1], ["effectivity-processor-2", 3], ["module-contact", 5], ["electronic-components", 5], ], am_type : "am6", result : 1, },
    "effectivity-module-2": { name : "effectivity-module-2", id : "effectivity-module-2", recipe : "effectivity-module-2", energy_required : 20, ingredients : [["effectivity-module", 1], ["effectivity-processor", 2], ["module-contact", 5], ], am_type : "am6", result : 1, },
    "effectivity-module": { name : "effectivity-module", id : "effectivity-module", recipe : "effectivity-module", energy_required : 10, ingredients : [["effectivity-processor", 1], ["module-case", 1], ["module-circuit-board", 1], ["module-contact", 4], ], am_type : "am6", result : 1, },
    "productivity-module-4": { name : "productivity-module-4", id : "productivity-module-4", recipe : "productivity-module-4", energy_required : 40, ingredients : [["productivity-module-3", 1], ["productivity-processor-2", 4], ["module-contact", 5], ["intergrated-electronics", 5], ], am_type : "am6", result : 1, },
    "productivity-module-3": { name : "productivity-module-3", id : "productivity-module-3", recipe : "productivity-module-3", energy_required : 30, ingredients : [["productivity-module-2", 1], ["productivity-processor-2", 3], ["module-contact", 5], ["electronic-components", 5], ], am_type : "am6", result : 1, },
    "productivity-module-2": { name : "productivity-module-2", id : "productivity-module-2", recipe : "productivity-module-2", energy_required : 20, ingredients : [["productivity-module", 1], ["productivity-processor", 2], ["module-contact", 5], ], am_type : "am6", result : 1, },
    "productivity-module": { name : "productivity-module", id : "productivity-module", recipe : "productivity-module", energy_required : 10, ingredients : [["productivity-processor", 1], ["module-case", 1], ["module-circuit-board", 1], ["module-contact", 4], ], am_type : "am6", result : 1, },
    "pollution-clean-module-4": { name : "pollution-clean-module-4", id : "pollution-clean-module-4", recipe : "pollution-clean-module-4", energy_required : 40, ingredients : [["pollution-clean-module-3", 1], ["pollution-clean-processor-2", 4], ["module-contact", 5], ["intergrated-electronics", 5], ], am_type : "am6", result : 1, },
    "pollution-clean-module-3": { name : "pollution-clean-module-3", id : "pollution-clean-module-3", recipe : "pollution-clean-module-3", energy_required : 30, ingredients : [["pollution-clean-module-2", 1], ["pollution-clean-processor-2", 3], ["module-contact", 5], ["electronic-components", 5], ], am_type : "am6", result : 1, },
    "pollution-clean-module-2": { name : "pollution-clean-module-2", id : "pollution-clean-module-2", recipe : "pollution-clean-module-2", energy_required : 20, ingredients : [["pollution-clean-module-1", 1], ["pollution-clean-processor", 2], ["module-contact", 5], ], am_type : "am6", result : 1, },
    "pollution-clean-module-1": { name : "pollution-clean-module-1", id : "pollution-clean-module-1", recipe : "pollution-clean-module-1", energy_required : 10, ingredients : [["pollution-clean-processor", 1], ["module-case", 1], ["module-circuit-board", 1], ["module-contact", 4], ], am_type : "am6", result : 1, },

	
	
	//replication
	"iron-ore": { category : "ore", name : "Iron Ore", id : "iron-ore", recipe : "repl-iron-ore", energy_required : 2.5, ingredients : [], am_type : "replicator5", result : 1, },
	"copper-ore": { category : "ore", name : "Copper Ore", id : "copper-ore", recipe : "repl-copper-ore", energy_required : 2.5, ingredients : [], am_type : "replicator5", result : 1, },
    "coal": { name : "Coal", id : "coal", recipe : "repl-coal", energy_required : 2.5, ingredients : [], am_type : "replicator5", result : 1, },
    "water": { category : "fluid", name : "Water", id : "coal", recipe : "repl-coal", energy_required : 2.5, ingredients : [], am_type : "replicator5", result : 1, },
    "tenemut": { name : "Tenemut", id : "tenemut", recipe : "repl-tenemut", energy_required : 3.5, ingredients : [], am_type : "replicator5", result : 1, },
    "ferric-chloride-solution": { category : "fluid", name : "Ferric Chloride Solution", id : "ferric-chloride-solution", recipe : "ferric-chloride-solution-alt", energy_required : 5.5, ingredients : [], am_type : "replicator5", result : 5, },
	"petroleum-gas": { category : "fluid", name : "Petroleum Gas", id : "petroleum-gas", recipe : "petroleum-gas-alt", energy_required : 10.5, ingredients : [], am_type : "replicator5", result : 5, },
    "heavy-oil": { category : "fluid", name : "Heavy Oil", id : "heavy-oil", recipe : "repl-heavy-oil", energy_required : 10.5, ingredients : [], am_type : "replicator5", result : 5, },
    "stone": { name : "Stone", id : "stone", recipe : "repl-stone", energy_required : 2.5, ingredients : [], am_type : "replicator5", result : 1, },
	"sulfuric-acid": { category : "fluid", name : "Sulfuric Acid", id : "sulfuric-acid", recipe : "repl-sulfuric-acid", energy_required : 58.5, ingredients : [], am_type : "replicator5", result : 5, },

};



